<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="cppExample\**" />
    <EmbeddedResource Remove="cppExample\**" />
    <None Remove="cppExample\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="game.cs" />
    <Compile Remove="MyArray.cs" />
  </ItemGroup>

</Project>
